### ISSUE TITLE
Mafia repl should not exit on CTRL+C

### ISSUE THREAD

**Issue by newhoggy** [haskell-mafia/mafia#130]
I just noticed that when I press CTRL+C inside `mafia repl`, the whole repl exits.

This differs from `ghci`, which breaks the current running expression but does not exit the repl.

**Comment by charleso** [comment]
This will be due to the `cabal` version you're running, nothing to do with mafia: https://github.com/haskell/cabal/issues/1448

I would _highly_ recommend `mafia quick`, (should be aliased as `mafia ghci`) which is better for this and other reasons.

**Comment by newhoggy** [comment]
Nice.  Thanks!!!
