### ISSUE TITLE
Error parsing output of `ghc-pkg list` in `hoogle` command edge case

### ISSUE THREAD

**Issue by ranweiler** [haskell-mafia/mafia#165]
## Summary
If we have an empty package database, say, in a new cabal sandbox, invocations of `mafia hoogle` will fail when attempting to parse the string "`(no packages)`".

## Observed
Create a new project with a minimal cabal file:
```bash
mkdir example
cd example
git init  # necessary!
cabal init -n --is-library -p example
cabal sandbox init
```
And we try the `hoogle` command on a prelude function:
```
mafia hoogle 'fst'
```
We get an exit code 1 and the message "Parse failed: Invalid package: no packages".

## Expected

Exit code 0 (since our query has results) and output like:
```
Combining 74 databases
Prelude fst :: (a, b) -> a
Data.Tuple fst :: (a, b) -> a
Foreign.StablePtr deRefStablePtr :: StablePtr a -> IO a
GHC.Prim deRefStablePtr# :: StablePtr# a -> State# (RealWorld) -> (# State# (RealWorld), a #)
GHC.PrimopWrappers deRefStablePtr# :: StablePtr# a -> State# (RealWorld) -> (# State# (RealWorld), a #)
GHC.StaticPtr deRefStaticPtr :: StaticPtr a -> a
```

## Notes
I'm using GHC 8.0.1 and `cabal-install` version 1.24.0.2.

In the setting above, with an empty sandbox package database, the output of `mafia exec ghc-pkg list` will be something like:
```
/usr/local/Cellar/ghc/8.0.1_4/lib/ghc-8.0.1/package.conf.d
    Cabal-1.24.0.0
    array-0.5.1.1
    base-4.9.0.0
    # ...
    transformers-0.5.2.0
    unix-2.7.2.0
    xhtml-3000.2.1
/Users/joe/tmp/example/.cabal-sandbox/x86_64-osx-ghc-8.0.1-packages.conf.d
    (no packages)
```
This suggest we are failing [here](https://github.com/ambiata/mafia/blob/master/src/Mafia/Hoogle.hs#L55) due to not filtering enough [here](https://github.com/ambiata/mafia/blob/master/src/Mafia/Hoogle.hs#L53).

If we don't need to relate packages to databases, an alternative would be to pass the `--simple-output` flag to the [call to `hc-pkg`](https://github.com/ambiata/mafia/blob/master/src/Mafia/Hoogle.hs#L52). Even in the broken case, this would result in space-delimited output like:
```
Cabal-1.24.0.0 array-0.5.1.1 base-4.9.0.0 binary-0.8.3.0 bytestring-0.10.8.1 containers-0.5.7.1 deepseq-1.4.2.0 directory-1.2.6.2 filepath-1.4.1.0 ghc-8.0.1 ghc-boot-8.0.1 ghc-boot-th-8.0.1 ghc-prim-0.5.0.0 ghci-8.0.1 haskeline-0.7.2.3 hoopl-3.10.2.1 hpc-0.6.0.3 integer-gmp-1.0.0.1 pretty-1.1.3.3 process-1.4.2.0 rts-1.0 template-haskell-2.11.0.0 terminfo-0.4.0.2 time-1.6.0.1 transformers-0.5.2.0 unix-2.7.2.0 xhtml-3000.2.1
```

**Comment by charleso** [comment]
@ranweiler Sorry for the sloppy bug, and good suggestion. Should be fixed now, let me know i that helps.

**Comment by ranweiler** [comment]
Looks good now, thanks @charleso!
