### ISSUE TITLE
`-Wmissing-home-modules` warning on fresh build

### ISSUE THREAD

**Issue by justanotherdot** [haskell-mafia/mafia#206]
For starters, using:

```bash
~/repos/mafia
η cabal --version
cabal-install version 2.0.0.1
compiled using version 2.0.1.0 of the Cabal library 
~/repos/mafia
η g
The Glorious Glasgow Haskell Compilation System, version 8.2.2

```

running `script/mafia` seems to cause a 'failed' build:

```bash
Preprocessing executable 'mafia' for ambiata-mafia-0.0.1..
Building executable 'mafia' for ambiata-mafia-0.0.1..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: BuildInfo_ambiata_mafia
                                                                                                 DependencyInfo_ambiata_mafia

<no location info>: error: 
Failing due to -Werror.
Process failed: cabal build -j --ghc-options=-Werror (exit code: 1)
```

However, mafia seems installed under `$HOME/.mafia/versions`, so I'm not sure if this actually failed

```
η mafia --version
mafia: 0.0.1-20180122212557-2e7e4d5
```

**Comment by justanotherdot** [comment]
Happy to make a PR for this but I'm assuming the advice given in the warning isn't the way to go.

**Comment by markhibberd** [comment]
If you list them in the executables other-modules it should be fine (just not libraries), but cabal itself has been broken and patched for this as it used to ignore other-modules for executables, so depending on your cabal version your mileage may vary anyway. 

It is a bit of a frustrating warning as it doesn’t solve an issue on executables like it does for libraries, it appears to be for more asthetic/consistency reasons which is not ideal.

**Comment by erikd** [comment]
@justanotherdot Unfortunately this is a warning issued by cabal itself. Supposedly this requires the use of an [autogen-modules](https://www.haskell.org/cabal/users-guide/developing-packages.html?highlight=autogen%20modules#autogenerated-modules
) stanza.

However, the easiest solution to avoid that warning is to downgrade to cabal-install 1.24. Version 1.24 is known to work with all GHC versions from 7.8 to 8.2 inclusive.

**Comment by justanotherdot** [comment]
Adding the `other-modules` clause seems to fix the warning and build error, but @erikd mentioned offline this might be an issue for earlier versions of `cabal-install`, so I'm reluctant to make a PR adding it into the cabal file. I could try testing on a different GHC/cabal-install pairing and see if anything blows up?

**Comment by erikd** [comment]
@justanotherdot I'll try it out in Mafia.

**Comment by justanotherdot** [comment]
Closing this since my issue's been resolved. Thanks for the help guys :+1:

**Comment by erikd** [comment]
i'd like to leave this open a bit longer while I play with potential solutions.

**Comment by erikd** [comment]
Testing in PR #207.

**Comment by justanotherdot** [comment]
Going to close again this as #207 seems to have been merged.
