### ISSUE TITLE
Support building with GHC 8.4

### ISSUE THREAD

**Issue by erikd** [haskell-mafia/mafia#217]
Adding this as an issue mainly to track the fact that some work has already been done. Current state of play is in the `topic/ghc_next` branch.

Current blocker is that in the test suite builds Hoogle 4.x using the current GHC version. This fails because Hoogle 4.x doesn't build with ghc 8.4 (Hoogle 5.0 was released in 2016). The obvious solution is to upgrade mafia to build and use a newer Hoogle version (assuming the same functionality can be provided). See #198 .

**Comment by tmcgilchrist** [comment]
Master version of mafia now supports Cabal 2.0 and GHC 8.4.
