### ISSUE TITLE
Possible fix for Mac OS X linker issues integrated into mafia?

### ISSUE THREAD

**Issue by justanotherdot** [haskell-mafia/mafia#221]
Ran into [this](https://github.com/Simspace/ld-wrapper-macos) awhile back and @jystic mentioned might be worth us integrating directly into mafia itself.

**Comment by erikd** [comment]
I'm on Linux so :see_no_evil: :hear_no_evil:  :speak_no_evil:.

However if you or someone else can integrate this neatly, then I'm all for it.

**Comment by justanotherdot** [comment]
> I'm on Linux so 🙈 🙉 🙊.

Same here, but I do have to use a Mac for work. I haven't yet run into it myself as of yet on High Sierra so I've nothing yet to reproduce to test again if I gave a fix a go.

**Comment by nhibberd** [comment]
https://phabricator.haskell.org/D4714

**Comment by justanotherdot** [comment]
> https://phabricator.haskell.org/D4714

@nhibberd does that actually fix it? I haven't tried yet. @markhibberd mentioned the `boris-http` module would be one place to test, but I couldn't replicate as I needed to get postgres installed to go further and lost focus.

**Comment by erikd** [comment]
@justanotherdot That fix works for the Cardano SL code base that was running into that problem.

**Comment by justanotherdot** [comment]
Nice 👌

**Comment by erikd** [comment]
It will be in 8.6 unless you roll your own earlier GHC with that fix backported.

**Comment by justanotherdot** [comment]
Should mafia be version aware and use this prior to 8.6?
