### ISSUE TITLE
quick doesn't support CPP version macros

### ISSUE THREAD

**Issue by charleso** [haskell-mafia/mafia#35]
```
Foo.hs:15:21:
     error: token is not a valid binary operator in a preprocessor subexpression
if MIN_VERSION_time(1,5,0)
    ~~~~~~~~~~~~~~~~^
1 error generated.
```

**Comment by jacobstanley** [comment]
some relevant info http://stackoverflow.com/questions/12546757/how-do-i-use-cabals-min-version-and-other-macros-with-ghci/12546758#12546758

**Comment by erikd-ambiata** [comment]
@charleso Pretty sure that works out of the box with ghc-8.0 but not with ghc-7.10 and earlier.

**Comment by jacobstanley** [comment]
@erikd-ambiata 👍 just checked this out, fails with 7.10, works with 8.0
