### ISSUE TITLE
Does not support multiple mafias initialising at same time

### ISSUE THREAD

**Issue by nhibberd** [haskell-mafia/mafia#36]

**Comment by olorin** [comment]
My default solution would just be have mafia wait on a lockfile under ~/.ambiata; would that solve the current issue?

**Comment by jacobstanley** [comment]
This is where the problem is:

``` sh
      mkdir -p $(dirname $MAFIA_PATH)
      cp "$MAFIA_TEMP/mafia/.cabal-sandbox/bin/mafia" "${MAFIA_PATH}.tmp"
      mv "${MAFIA_PATH}.tmp" "$MAFIA_PATH"
```

The issue is that `$MAFIA_PATH` is not random, and it should be really.

**Comment by jacobstanley** [comment]
well `$MAFIA_PATH` shouldn't be random, but `${MAFIA_PATH}.tmp` should be
