### ISSUE TITLE
Don't fail when emacs backup files are present

### ISSUE THREAD

**Issue by olorin** [haskell-mafia/mafia#86]
Especially not with "Could not find cabal file". Will fix this later today.

**Comment by thumphries** [comment]
[bug is here](https://github.com/ambiata/mafia/blob/cadb3fa4e82abecf3262e41cd29136a8c09891bf/src/Mafia/Cabal/Package.hs#L48)

**Comment by thumphries** [comment]
ignoring hidden files in that function seems reasonable

**Comment by olorin** [comment]
Yeah, that's my plan.
