### ISSUE TITLE
Unable to build submodule dependencies

### ISSUE THREAD

**Issue by newhoggy** [haskell-mafia/mafia#99]
Trying to get submodule source dependency to build for the first time.  Getting "Process failed: cabal install" error.

```
✔ ~/wrk/haskell-works/hw-all [master L|✚ 2]
09:49 $ git submodule
 e50000fdda4cbe4ad69755aa6cdca0dcd94c8f3e hw-bits (heads/master)
 634735257f9e878dcefad471a7cd948174fdd677 hw-diagnostics (heads/master)
 83e71d6035e3eb58d25b3043e18fa34bc94ccaec hw-succinct (heads/master)
09:49 $ cd hw-succinct/
✔ ~/wrk/haskell-works/hw-all/hw-succinct [master|✚ 1…1]
09:50 $ mafia build
Installing dependencies...
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: hw-succinct-0.0.0.4 (user goal)
next goal: hw-diagnostics (dependency of hw-succinct-0.0.0.4)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
Process failed: cabal install --reorder-goals --max-backjumps=-1 --avoid-reinstalls --dry-run --enable-tests --enable-benchmarks --enable-profiling (exit code: 1)
```

**Comment by thumphries** [comment]
`mafia` finds projects relative to the nearest git root. when you run it from inside a submodule it won't know about the other submodules, i.e. right now it doesn't work for this kind of meta-repository. if you create submodules inside `hw-succinct` pointing to the other two, it should work.

this could be supported fairly easily I think. e.g. a flag to tell it where the root is.

**Comment by markhibberd** [comment]
You can manually specify submodule location with a <project>.submodules file where project matches cabal file name. File is newline seperated paths relative to fit root of current module. So something like ../hw-diagnostics will add the sibling submodule to build.

**Comment by jacobstanley** [comment]
@newhoggy I'd recommend you set up your `hw-succinct` repository such that it has `hw-diagnostics` as a submodule inside a `lib` directory:

```
hw-succinct (git root)
 └─╼ lib
      ├─╼ hw-diagnostics (submodule)
      └─╼ (other submodules)
```

[Icicle](https://github.com/ambiata/icicle/tree/master/lib) is an example of this setup.

Either that, or you can put all of your projects in the same git repository, and mafia will also find them, given how they are named, perhaps this is better, not sure:

```
hw-all (git root)
├─╼ hw-bits (just a directory, not a submodule)
├─╼ hw-diagnostics (not a submodule)
├─╼ hw-succint (not a submodule)
└─╼ lib
      └─╼ (other submodules)
```

[Mismi](https://github.com/ambiata/mismi) is an example of this setup.

**Comment by newhoggy** [comment]
Thanks!  I've confirmed that this setup is working:

```
hw-succinct (git root)
 └─╼ lib
      ├─╼ hw-diagnostics (submodule)
      └─╼ (other submodules)
```

The `.submodules` method isn't working for me for some reason though:

```
✔ ~/wrk/haskell-works/hw-succinct [master|✚ 2…1]
16:04 $ ls ../hw-bits/
LICENSE         README.md       Setup.hs        app         bench           circle.yml      hw-bits.cabal       install-stack.sh    src         stack.yaml      test
✔ ~/wrk/haskell-works/hw-succinct [master|✚ 2…1]
16:04 $ cat .submodules
../hw-bits
✔ ~/wrk/haskell-works/hw-succinct [master|✚ 2…1]
16:04 $ mafia build
Installing dependencies...
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: hw-succinct-0.0.0.4 (user goal)
next goal: hw-bits (dependency of hw-succinct-0.0.0.4)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
Process failed: cabal install --reorder-goals --max-backjumps=-1 --avoid-reinstalls --dry-run --enable-tests --enable-benchmarks --enable-profiling (exit code: 1)
```

**Comment by nhibberd** [comment]
I believe the filename needs to be `<project-name>.submodules`. So `hw-succinct.submodules` in your case

**Comment by newhoggy** [comment]
Yep. That was the reason.  Thanks!
